# Generated by Django 2.2.5 on 2020-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200209_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('gitgub', 'Github'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
