# Generated by Django 2.2.5 on 2020-01-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200125_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenitys',
            new_name='amenities',
        ),
    ]
