# Generated by Django 2.2.5 on 2020-01-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_photo_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='host',
        ),
    ]
